version: "3.8"
services:
  erp-mysql:
    image: mysql:8.0
    restart: always
    container_name: ice-mysql
    networks:
      - ice-network
    ports:
      - "23307:3306"
    environment:
      - MYSQL_DATABASE=bacchus_ice_db
      - MYSQL_ROOT_PASSWORD=root123456
      - TZ=Asia/Seoul
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --lower_case_table_names=1
    volumes:
      - ice-mysql-data:/var/lib/mysql
      - "./init.sql:/docker-entrypoint-initdb.d/init.sql"

volumes:
  ice-mysql-data:

networks:
  ice-network:
      name: ice-network